const { contextBridge, ipcRenderer } = require("electron");

const channels = [
  "config:get",
  "folder:save",
  "folder:remove",
  "filters:save",
  "profile:destination",
  "profile:override",
  "profile:selectFolder",
  "profile:selectItems",
  "device:rename",
  "device:remove",
  "settings:reset",
  "pick:folder",
  "library:list",
  "library:gameSizes",
  "library:reveal",
  "device:status",
  "storage:browse",
  "storage:size",
  "storage:mkdir",
  "storage:delete",
  "storage:pickFiles",
  "storage:upload",
  "storage:download",
  "storage:cancel",
  "inventory:status",
  "sync:check",
  "sync:start",
  "sync:cleanTemps",
  "sync:cancel",
  "session:status",
  "session:takeBack",
  "web:configure",
  "device:merge",
  "device:lowImpact",
  "web:restart",
  "app:startup",
  "media:thumbs",
  "media:details",
  "steam:search",
  "steam:resolve",
  "scrape:start",
  "scrape:cancel",
  "scrape:systems",
  "scraping:configure",
  "scraping:test",
  "profile:option",
  "gamenative:configs",
  "gamenative:save",
];

contextBridge.exposeInMainWorld("odin", {
  mode: "app",
  invoke: (channel, ...args) => {
    if (!channels.includes(channel)) throw new Error("Unsupported operation");
    return ipcRenderer.invoke(channel, ...args);
  },
  onProgress: (callback) => ipcRenderer.on("sync:progress", (_event, value) => callback(value)),
  onScrape: (callback) => ipcRenderer.on("scrape:progress", (_event, value) => callback(value)),
  onDeviceState: (callback) => ipcRenderer.on("device:state", (_event, value) => callback(value)),
  onSession: (callback) => ipcRenderer.on("session:changed", (_event, value) => callback(value)),
  onStorage: (callback) => ipcRenderer.on("storage:progress", (_event, value) => callback(value)),
});
